config/routes.rb
Rails.application.routes.draw do
  resources :friends
  resources :statistics
  resources :chess_games
  resources :players
  resources :game_saves
  resources :chess_pieces
  devise_for :users
  get 'home/hello'

end

app/models/chess_game.rb
class ChessGame < ActiveRecord::Base
   belongs_to :player_white_id, :class_name => 'Player'
   belongs_to :player_black_id,:class_name => 'Player'
   has_many :game_saves
   
 end

app/controllers/chess_games_controller.rb
class ChessGamesController < ApplicationController
  before_action :set_chess_game, only: [:show, :edit, :update, :destroy]

  # GET /chess_games
  # GET /chess_games.json
  def index
    @chess_games = ChessGame.all
  end

  # GET /chess_games/1
  # GET /chess_games/1.json
  def show
  end

  # GET /chess_games/new
  def new
    @chess_game = ChessGame.new
  end

  # GET /chess_games/1/edit
  def edit
  end

  # POST /chess_games
  # POST /chess_games.json
  def create
    @chess_game = ChessGame.new(chess_game_params)

    respond_to do |format|
      if @chess_game.save
        format.html { redirect_to @chess_game, notice: 'Chess game was successfully created.' }
        format.json { render :show, status: :created, location: @chess_game }
      else
        format.html { render :new }
        format.json { render json: @chess_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chess_games/1
  # PATCH/PUT /chess_games/1.json
  def update
    respond_to do |format|
      if @chess_game.update(chess_game_params)
        format.html { redirect_to @chess_game, notice: 'Chess game was successfully updated.' }
        format.json { render :show, status: :ok, location: @chess_game }
      else
        format.html { render :edit }
        format.json { render json: @chess_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chess_games/1
  # DELETE /chess_games/1.json
  def destroy
    @chess_game.destroy
    respond_to do |format|
      format.html { redirect_to chess_games_url, notice: 'Chess game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chess_game
      @chess_game = ChessGame.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chess_game_params
      params.require(:chess_game).permit(:gameType, :accessCode, :publicMatch)
    end
end

app/helpers/chess_games_helper.rb
module ChessGamesHelper
end

app/views/chess_games/_form.html.erb
<%= form_for(@chess_game) do |f| %>
  <% if @chess_game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chess_game.errors.count, "error") %> prohibited this chess_game from being saved:</h2>

      <ul>
      <% @chess_game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :gameType %><br>
    <%= f.text_field :gameType %>
  </div>
  <div class="field">
    <%= f.label :accessCode %><br>
    <%= f.text_field :accessCode %>
  </div>
  <div class="field">
    <%= f.label :publicMatch %><br>
    <%= f.check_box :publicMatch %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chess_games/edit.html.erb
<h1>Editing Chess Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @chess_game %> |
<%= link_to 'Back', chess_games_path %>

app/views/chess_games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Chess Games</h1>

<table>
  <thead>
    <tr>
      <th>Gametype</th>
      <th>Accesscode</th>
      <th>Publicmatch</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chess_games.each do |chess_game| %>
      <tr>
        <td><%= chess_game.gameType %></td>
        <td><%= chess_game.accessCode %></td>
        <td><%= chess_game.publicMatch %></td>
        <td><%= link_to 'Show', chess_game %></td>
        <td><%= link_to 'Edit', edit_chess_game_path(chess_game) %></td>
        <td><%= link_to 'Destroy', chess_game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chess game', new_chess_game_path %>

app/views/chess_games/new.html.erb
<h1>New Chess Game</h1>

<%= render 'form' %>

<%= link_to 'Back', chess_games_path %>

app/views/chess_games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Gametype:</strong>
  <%= @chess_game.gameType %>
</p>

<p>
  <strong>Accesscode:</strong>
  <%= @chess_game.accessCode %>
</p>

<p>
  <strong>Publicmatch:</strong>
  <%= @chess_game.publicMatch %>
</p>

<%= link_to 'Edit', edit_chess_game_path(@chess_game) %> |
<%= link_to 'Back', chess_games_path %>